name: Publish NPM Package

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
          always-auth: true
          registry-url: 'https://registry.npmjs.org/'
    
      - name: update API_URL
        run: sed -i 's|{{API_URL}}|${{ secrets.API_URL }}|g' src/consts.ts
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Package
        run: npm run rollup
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
